dist: trusty
sudo: required
language:
    - cpp

compiler:
    - g++

notifications:
    email: false

# Install project dependencies
install:
    - bash get_dependencies.sh

# Build the project
script:
    # Build INS server
    - bash server/build_and_run_ut.sh
    - bash ins-node/build_and_run_ut.sh
