dist: trusty
sudo: required
language:
    - cpp

compiler:
    - g++
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3-8

notifications:
    email: false

# Install project dependencies
install:
    - "[ $CXX = g++ ] && export CXX=g++-6 || true"
    - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
    - bash get_dependencies.sh 

# Build the project
script:
    # Build INS server
    - bash server/build_and_run_ut.sh
    - bash ins-node/build_and_run_ut.sh
